Inventario/Models/Log.cs
namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Log")]
    public partial class Log
    {
        public int Id { get; set; }

        public int Product_id { get; set; }

        [Column(TypeName = "smalldatetime")]
        public DateTime Datetime { get; set; }

        [Required]
        [StringLength(7)]
        public string Type { get; set; }

        public long? Serial { get; set; }

        public virtual Product Product { get; set; }
    }
}

Inventario/Models/Product.cs
namespace Inventario.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Product")]
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            Log = new HashSet<Log>();
        }

        public int Id { get; set; }

        [Display(Name = "Producto")]
        public int Caproduct_id { get; set; }

        [Display(Name = "Pedido")]
        [Required]
        public  int Order_id { get; set; }

        [Display(Name = "Largo")]
        public float Long { get; set; }

        [Display(Name = "Ancho")]
        public float Width { get; set; }

        [Required]
        [StringLength(15)]
        public string Color { get; set; }

        public long Barcode { get; set; }

        [Display(Name = "Cantidad")]
        public int Quantity { get; set; }

       
        public virtual Order Order { get; set; }

        public virtual CaProduct CaProduct { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Log> Log { get; set; }
    }
}

Inventario/Controllers/Api/LogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Inventario.Models;
using System.Data.Entity;
using Inventario.Models.DTO;

namespace Inventario.Controllers.Api
{
    public class LogController : ApiController
    {
        private BarcodeDBEntities _context;

        public LogController()
        {
            _context = new BarcodeDBEntities();
        }

        public IHttpActionResult GetLogs()
        {
            var logs = _context.Log.Include(l => l.Product).Include(l => l.Product.CaProduct).Include(l => l.Product.Order).ToList();
            return Ok(logs);
        }

        public IHttpActionResult CreateLogs(LogBarcodeDto logBarcode)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var product = _context.Product.FirstOrDefault(p => p.Barcode == logBarcode.Barcode);
            if (product == null)
                return NotFound();
            var log = new Log {
                Product_id = product.Id,
                Datetime = DateTime.Now,
                Type = logBarcode.Type
            };
            _context.Log.Add(log);
            _context.SaveChanges();
            return Ok("success");
            //return Conflict(); para bajas en 0
        }
    }
}

Inventario/Controllers/Api/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Inventario.Models;

namespace Inventario.Controllers.Api
{
    public class ProductController : ApiController
    {
        private BarcodeDBEntities _context;

        public ProductController()
        {
            _context = new BarcodeDBEntities();
        }

        // GET /api/products
        public IHttpActionResult GetProducts()
        {
            var products = _context.Product.Include(c=>c.CaProduct).Include(c=>c.Order)
                .ToList();
            return Ok(products);
        }
    }
}

Inventario/Controllers/OrderController.cs
using Inventario.Helper;
using Inventario.Models;
using Inventario.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inventario.Controllers
{
   
    public class OrderController : Controller
    {
        private BarcodeDBEntities _context;
        private Label label;
        public OrderController()
        {
            _context = new BarcodeDBEntities();
            label = new Label();
        }
        // GET: Order
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult New()
        {
            var viewModel = new OrderFormViewModel {
                Customers = _context.Customer.ToList(),
                Colors = _context.Color.ToList(),
                CaProducts = _context.CaProduct.ToList(),
                Product = new Product { Id = 0, Quantity = 0 }
            };
            return View(viewModel);
        }

        public ActionResult Save(ICollection<Product> products, Order order)
        {
            int val = 11;
            string res="", msg="";
            using (var transaction = _context.Database.BeginTransaction())
            {
                try
                {
                    Order orderdb = _context.Order.Add(order);
                    _context.SaveChanges();
                   // transaction.Commit();
                    foreach (var product in products)
                    {
                        product.Order_id = orderdb.Id;
                        string str = DateTime.Now.ToString("yyyyMMddHHmmss");
                        str = str + (val);
                        product.Barcode = Convert.ToInt64(str);
                        _context.Product.Add(product);
                        _context.SaveChanges();
                        label.create(product.Barcode.ToString());
                        val++;
                    }
                    transaction.Commit();
                    res = "success"; msg="Pedido Guardado";
                }
                catch (Exception ex)
                {
                    Debug.WriteLine(ex.ToString());
                    transaction.Rollback();
                    res = "error";msg = "Error al guardar";
                }
            }
            return Json(new {res=res,msg=msg });
        }
    }
}

Inventario/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Inventario.Models;
using Inventario.ViewModels;
using Inventario.Helper;
using System.Net;
using System.IO;
using System.Data.Entity;
using System.Data;
using ClosedXML.Excel;
using BarcodeLib;
using System.Drawing;

namespace Inventario.Controllers
{
   
    public class ProductController : Controller
    {
        private BarcodeDBEntities _context;
        private Label label;
        public ProductController()
        {
            _context = new BarcodeDBEntities();
            label = new Label();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        [Authorize(Roles = "Admin, User")]
        public ActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "Admin, User")]
        public ActionResult Report()
        {
            var products = _context.Product.Include(c => c.CaProduct).Include(c => c.Order)
               .ToList();
            DataTable dt = new DataTable("Product");
            dt.Columns.AddRange(new DataColumn[10] { new DataColumn("Folio"),
                                            new DataColumn("Cliente"),
                                            new DataColumn("Producto"),
                                            new DataColumn("Color"),
                                            new DataColumn("Ancho"),
                                            new DataColumn("Largo"),
                                            new DataColumn("Material en piso"),
                                            new DataColumn("Metros Cuadrados"),
                                            new DataColumn("Peso"),
                                            new DataColumn("Destino")
            });
            dt.Columns[7].DataType = typeof(Double);
            dt.Columns[6].DataType = typeof(Double);
            dt.Columns[5].DataType = typeof(Int64);
            foreach (var product in products)
            {
                if (product.Quantity < 1)
                    continue;
                var m2 = product.Quantity * product.Long * product.Width;
                dt.Rows.Add(product.Order.Folio,product.Order.Customer.Name ,product.CaProduct.Name, product.Color, product.Width,
                            product.Long, product.Quantity, m2, m2*product.CaProduct.Weight,product.Order.Place);
            }
            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return base.File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Material en piso "+DateTime.Now+".xlsx");
                }
            }
            //return RedirectToAction("Index", "Product"); 

        }

        [Authorize(Roles = "Admin, User")]
        public ActionResult Log()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Reportlog()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin, User")]
        public ActionResult ReportLogPost(DateTime dateinitial, DateTime datefinal)
        {
           datefinal= datefinal.AddHours(23);
           datefinal= datefinal.AddMinutes(59);
            var logs = _context.Log.Include(l => l.Product).Include(l => l.Product.CaProduct).
                Where(l=>l.Datetime >= dateinitial && l.Datetime <= datefinal).ToList();

            DataTable dt = new DataTable("Log");
            dt.Columns.AddRange(new DataColumn[7] { 
                                            new DataColumn("Producto"),
                                            new DataColumn("Color"),
                                            new DataColumn("Ancho(M)"),
                                            new DataColumn("Largo(M)"),
                                            new DataColumn("Pedido"),
                                            new DataColumn("Fecha"),
                                            new DataColumn("Tipo")
            });

            foreach (var log in logs)
            {
                dt.Rows.Add( log.Product.CaProduct.Name, log.Product.Color, log.Product.Width,
                            log.Product.Long, log.Product.Order.Folio, log.Datetime.ToString("yyyy-MM-dd"), log.Type);
            }
            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return base.File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Logs " + DateTime.Now + ".xlsx");
                }
            }
            //return RedirectToAction("Index", "Product"); 
        }

        [Authorize(Roles = "Admin")]
        public ActionResult New()
        {
            //long barcode = Convert.ToInt64(DateTime.Now.ToString("yyyyMMddHHmmss"));
            var viewModel = new ProductFormViewModel
            {
                CaProducts = _context.CaProduct.OrderBy(p=>p.Name).ToList(),
                Colors = _context.Color.OrderBy(c=>c.Name).ToList(),
                Product = new Product { Id = 0, Quantity=0 }
            };
            return View(viewModel);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create(Product product)
        {
            if (product.Id == 0)
            {
                product.Barcode = Convert.ToInt64(DateTime.Now.ToString("yyyyMMddHHmmss"));
                _context.Product.Add(product);
                _context.SaveChanges();
                string code = Convert.ToString(product.Barcode);
                label.create(code);
                //webClient.DownloadFile(Server.MapPath("~/labels/" + code + ".jpg"), code+".jpg");
                //webClient.DownloadFile("http://localhost:50147/Product/Index",Server.MapPath("~/labels/" + code + ".jpg"));
            }
            return RedirectToAction("Index","Product");
        }

        [Authorize(Roles = "Admin, User")]
        public ActionResult Label(string id)
        {
            
            var dir = Server.MapPath(" ~/Content/labels");
            var path = Path.Combine(dir, id + ".jpg"); //validate the path for security or use other means to generate the path.
            return base.File(path, "image/jpeg");
        }

        public void saveLabel(string code)
        {
            Barcode barcode = new BarcodeLib.Barcode();
            barcode.IncludeLabel = true;
            Image img = barcode.Encode(BarcodeLib.TYPE.CODE128, code, System.Drawing.Color.Black, System.Drawing.Color.White, 300, 150);
            var dir = Server.MapPath(" ~/Content/labels");
            string path = Path.Combine(dir, code,  ".jpg");
            barcode.SaveImage(path, BarcodeLib.SaveTypes.JPG);
            //barcode.SaveImage(HttpContext.Current.Server.MapPath("~/Content/labels/" + code + ".jpg"), BarcodeLib.SaveTypes.JPG);
            //barcode.SaveImage(HttpContext.Current.Server.MapPath("~/Content/labels/" + code + ".jpg"), BarcodeLib.SaveTypes.JPG);

            //barcode.SaveImage(Url.c), BarcodeLib.SaveTypes.JPG);

        }
    }
}

Inventario/Views/Product/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Inventario/Views/Product/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<h2>Productos</h2>
@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Nuevo Pedido", "New", "Order", null, new { @class = "btn btn-primary" })
    </p>
}
<div class="panel panel-default panel-main">
    <div class="panel-heading">Listado de productos</div>
    <div class="panel-body">
        <div class="table-responsive">
            <table id="tblproduct" class="table table-striped">
                <thead>
                    <tr>
                        <th>Pedido</th>
                        <th>Cliente</th>
                        <th>Producto</th>
                        <th>Color</th>
                        <th>Largo (M)</th>
                        <th>Ancho (M)</th>
                        <th>M. en Piso</th>
                        <th>M2</th>
                        <th>Peso</th>
                        <th>Codigo</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>
@section scripts
{
<script>
    $(document).ready(function () {
        var table = $("#tblproduct").DataTable({
            ajax: {
                url: "/api/product",
                dataSrc: ""
            },
            columns: [
                {
                    data: "Order.Folio"
                },
                {
                    data: "Order.Customer.Name"
                },
                {
                    data: "CaProduct.Name",
                    render: function (data, type, product) {
                       // return "<a href='/product/edit/" + product.Id + "'>" + data + "</a>";
                        return "<a href='#'>" + data + "</a>";
                    }
                },
                {
                    data: "Color"
                },
                {
                    data: "Long"
                },
                {
                    data: "Width"
                },
                {
                    data: "Quantity"
                },
                {
                    data: "id",
                    render: function (data, type, product) {
                        var m2 = product.Long * product.Width * product.Quantity;
                        return m2.toFixed(3);
                    }
                },
                {
                    data: "id",
                    render: function (data, type, product) {
                        var peso = product.Long * product.Width * product.Quantity * product.CaProduct.Weight;
                        return peso.toFixed(3);
                    }
                },
                {
                    data: "Barcode",
                    render: function (data, type, product) {
                        return "<a href='/product/label/" + data + "'>"+data+"</a>";
                    }
                }
              
            ]
        });//Datatable
    });//Documen.ready
</script>
}

Inventario/Views/Product/Log.cshtml
@{
    ViewBag.Title = "Entradas y Salidas";
}
<h2>Entradas y salidas de confeccion</h2>

<div class="panel panel-default panel-main">
    <div class="panel-heading">Listado de entradas y salidas</div>
    <div class="panel-body">
        <div class="table-responsive">
            <table id="tbllog"  class="table table-striped">
            <thead>
                <tr>
                    <th>Producto</th>
                    <th>Color</th>
                    <th>Largo (M)</th>
                    <th>Ancho (M)</th>
                    <th>Pedido</th>
                    <th>Fecha</th>
                    <th>Tipo</th>
                </tr>
            </thead>
            <tbody>
              
            </tbody>
            </table>
        </div>
    </div>
</div>
@section scripts
{
    <script>
    $(document).ready(function () {
        var table = $("#tbllog").DataTable({
            ajax: {
                url: "/api/log",
                dataSrc: ""
            },
            columns: [
                {
                    data: "Product.CaProduct.Name"
                },
                {
                    data: "Product.Color"
                },
                {
                    data: "Product.Long"
                },
                {
                    data: "Product.Width"
                },
                {
                    data: "Product.Order.Folio"
                },
                {
                    data: "Datetime",
                    render: function (data) {
                        return formatDate(data);
                    }
                },
                {
                    data: "Type",
                    render: function (data) {
                        if (data == "ENTRADA") {
                            return "<button class='btn btn-xs btn-success'>" + data + "</button>";
                        }
                        else {
                            return "<button class='btn btn-xs btn-danger'>" + data + "</button>";
                        }
                    }
                }
            ]
        });//Datatable
        });//Documen.ready

        function formatDate(date) {
            date = new Date(date);
            year = date.getFullYear();
            month = date.getMonth() + 1;
            dt = date.getDate();
            if (dt < 10) {
                dt = '0' + dt;
            }
            if (month < 10) {
                month = '0' + month;
            }
            return (year + '/' + month + '/' + dt);
        }
    </script>
}

Inventario/Views/Product/New.cshtml
@model Inventario.ViewModels.ProductFormViewModel
@{
    ViewBag.Title = "New Product";
}

<h2>Nuevo Producto</h2>
@using (Html.BeginForm("Create", "Product",FormMethod.Post)) {
    @Html.HiddenFor(p=>p.Product.Id)
    <div class="form-group">
        @Html.LabelFor(p=>p.Product.Caproduct_id)
        @Html.DropDownListFor(p=>p.Product.Caproduct_id,new SelectList(Model.CaProducts,"Id","Name"),"Selecciona Producto", new { @class = "form-control"})
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Product.Color)
        @Html.DropDownListFor(p => p.Product.Color, new SelectList(Model.Colors, "Name", "Name"), "Selecciona Color", new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Product.Width)
        @Html.TextBoxFor(p => p.Product.Width, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.Product.Width, null, new { @class = "alert-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Product.Long)
        @Html.TextBoxFor(p => p.Product.Long, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.Product.Long, null, new { @class = "alert-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Product.Quantity)
        @Html.TextBoxFor(p => p.Product.Quantity, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.Product.Quantity, null, new { @class = "alert-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Product.Order)
        @Html.TextBoxFor(p => p.Product.Order, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.Product.Order, null, new { @class = "alert-danger" })
    </div>
    <button type="submit" class="btn btn-primary">Guardar</button>
}

Inventario/Views/Product/Reportlog.cshtml
@{
    ViewBag.Title = "Reporte de Piso";
}

<h2>Reporte de Entradas y Salidas</h2>
<h6>Seleccione el rango de fecha del reporte</h6>
@using (Html.BeginForm("ReportLogPost", "Product", FormMethod.Post))
{
    @Html.ValidationSummary()
    <div class="form-group">
        @Html.Label("Fecha Inicial")
        @Html.TextBox("dateinitial", DateTime.Now.ToString("yyyy-MM-dd"), new { @class = "form-control", @data_val = "true", @data_val_required = "Fecha inicial requerida", type="date"})
        @Html.ValidationMessage("dateinitial", null, new { @class = "alert-danger" })
    </div>
    <div class="form-group">
        @Html.Label("Fecha Final")
        @Html.TextBox("datefinal", DateTime.Now.ToString("yyyy-MM-dd"), new { @class = "form-control", @data_val = "true", @data_val_required = "Fecha inicial requerida", type = "date" })
        @Html.ValidationMessage("datefinal", null, new { @class = "alert-danger" })
    </div>
  
    <button type="submit" class="btn btn-primary">Aceptar</button>
}